### ISSUE TITLE
What is difference between include (t, value) and contains (t, value)

### ISSUE THREAD

**Issue by takaaptech** [Yonaba/Moses#16]
As title say, i have a bit confuse about two functions above in Table functions (https://github.com/Yonaba/Moses/blob/master/doc/tutorial.md) , are they equal?

**Comment by zackthehuman** [comment]
It seems like they are functionally the same, except that `_.contains` may have slightly lower performance since it's implemented in terms of `_.detect`.

**Comment by Yonaba** [comment]
They are perfectly equal, thanks for bringing this up. I'll remove the actual implementation of `_.contains` and leave it as an alias to `_.include`.

**Comment by Yonaba** [comment]
Now fixed. 
Thanks @takaaptech and @zackthehuman.
