### ISSUE TITLE
working with matrix

### ISSUE THREAD

**Issue by denisdemais** [Yonaba/Moses#23]
Hi. I'm new on function programming-like.

moses works fine with array, i.e.
tbl = {id=1, value=12.23};

but with i can work
tbl = {
{id=1, value=12.23},
{id=2, value=32.33
[...]
};

i have to select? or how can process/find/sort using this data movel

sugesstion: add functions to de/serialize using files

**Comment by Yonaba** [comment]
Hi @denisdemais,

This issue has been closed without much explanation. Actually, can you please explain what you wanted to do ? Maybe I can provide some hints on how to use Moses to that purpose ?
Thanks.
Otherwise, I'll close back this issue.

**Comment by denisdemais** [comment]
@Yonaba 
I'm new on functional languages.
some aspects of moses/underscores-like are poor documented or useless examples.

I was try uses underscore.lua and moses.lua and after some hours... i can uses with success.

now i can processing json (to lua) easy!
mongodb json input -> lua -> moses processing -> output ok -> that's ok!
moses help to reduce procedural code (a lot)!

thanks!

PS:
add a _.version() -> { 'moses', 'uri', '1.xx' } | 'moses 1.30 http://....'
