### ISSUE TITLE
_.all  is implemented as a array function , but in the tutorial.md , it is in the group of table functions .

### ISSUE THREAD

**Issue by yuliying** [Yonaba/Moses#25]
the original code is : 
function _.all(t, f, ...)
      return ((#_.select(_.map(t,f,...), isTrue)) == (#t))
end

may be 
function _.all(t, f, ...)
      return ((#_.select(_.map(t,f,...), isTrue)) == count(t) )
end
is right?

**Comment by Yonaba** [comment]
Good point. Thanks @yuliying.
