### ISSUE TITLE
behavior : _.isNumber()  _.isInteger()

### ISSUE THREAD

**Issue by denisdemaisbr** [Yonaba/Moses#27]
**values with [ "" ], i.e., '0', '1.1', ...  are not valid**

sugest:
_maybe a flag can 'help' with this _.isNumber( value, [true] ) can force a number/integer convert/cast._

$ cat test.moses.isnumber.lua
_ = dofile('moses.lua')
tbl = { 1, 1.99, .99, -1, 0, '', '0', '1', '1.1', '-1', false, nil }
_.eachi( tbl, function(i, v) print( i, tostring(v), _.isNumber(v), _.isInteger(v) ) end)

--- output
1       1       true    true
2       1.99    true    false
3       0.99    true    false
4       -1      true    true
5       0       true    true
6               false   false
7       0       false   false
8       1       false   false
9       1.1     false   false
10      -1      false   false
11      false   false   false

**Comment by Yonaba** [comment]
Hi @denisdemaisbr
Much thanks for the idea. But unfortunately, I do not think so. The intended behavior behind `_.isNumber()` and `_.isInteger()` is purely related to the intrinsic type of the data, not that if the data can be converted to a number/integer.
