### ISSUE TITLE
Two small spelling mistakes in the tutorials

### ISSUE THREAD

**Issue by RussellHaley** [Yonaba/Moses#32]
Two small spelling mistakes in the tutorials:
https://github.com/Yonaba/Moses/blob/master/doc/tutorial.md

pluck (t, property)
Fetches all values indxed with specific key in a table of objects. 
*indxed ->indexed*

constant (value)
Creates a constant function. This function will constinuously yield the same output.
*constinuously -> continuously*

Cheers,
Russ

**Comment by Yonaba** [comment]
Much thanks, @RussellHaley !
