### ISSUE TITLE
Feature request: findWhere(t, f)

### ISSUE THREAD

**Issue by Kinrany** [Yonaba/Moses#40]
Extend `findWhere` to accept a function as it's second argument instead of a table.

For example, find the first even number in a table:

``` lua
t = {1, 2, 3}
result = __.findWhere(t, function(value)
    return value % 2 == 0
end)
print(result) --> 2
```

**Comment by Yonaba** [comment]
Actually, [`detect`](https://github.com/Yonaba/Moses/blob/master/doc/tutorial.md#detect-t-value) already does that perfectly.
