### ISSUE TITLE
Feature request: unpack()

### ISSUE THREAD

**Issue by drauschenbach** [Yonaba/Moses#43]
The global unpack() was deprecated in Lua 5.3, and moved to the table module. Therefore, lots of Lua programs, including Moses, contain a line like this:

```lua
local unpack = table.unpack or unpack
```

This makes it useful to everyone. It'd be nice to not have such lines in my programs, and instead call Moses:

```lua
local x,y = moses.unpack(array)
```

**Comment by Yonaba** [comment]
Nice idea. It has been added via commit 333aa5a.
Thanks.

**Comment by drauschenbach** [comment]
Sweet!
