### ISSUE TITLE
sample() fails when array contains middleclass classes

### ISSUE THREAD

**Issue by drauschenbach** [Yonaba/Moses#44]
The `sample(array, numSamples)` function seems to be sensitive to datatypes allowed in the array argument, and fails to return any array elements when an array contains middleclass class instances.

Test using Busted:

```lua
local class = require 'middleclass'
local moses = require 'moses'

describe('moses sample()', function()

  it('works when array contains Vector classes', function()

    local DenseVector = class('DenseVector')
    function DenseVector:initialize(data)
      self.data = data
    end

    local vector1 = DenseVector:new({1,2,3})
    local vector2 = DenseVector:new({4,5,6})

    local sample = moses.sample({vector1, vector2}, 1)
    assert.equal(1, #sample) -- <== fails because #sample is 0
    assert.is_true(sample[1]:isInstanceOf(DenseVector)) -- <== never runs
  end)

end)
```

**Comment by drauschenbach** [comment]
Oh I see. Functions that return different datatypes for n=1 are very unexpected, unchainable, and "not inspired by lodash". Such functions would also require the caller to have an "if n=1" condition. I suggest that such functions are unusable.

**Comment by Yonaba** [comment]
Strong point, taken into consideration. See commit d7e9618 which reflect the changes.

**Comment by drauschenbach** [comment]
Looks better. The function still returns a non-array for n<1, which causes the same problem. What's the purpose of having special handling for n=1? Doesn't having different codepaths for different parameter values lead to inconsistencies?

**Comment by Yonaba** [comment]
It is fixed as of now.
Thanks for your feedback.

**Comment by drauschenbach** [comment]
Sweet 👍

**Comment by drauschenbach** [comment]
BTW, your last publish to LuaRocks was 225 days ago. You've worked on a lot of goodies since then! You can share more often -- we won't mind! :-)
