### ISSUE TITLE
Don't treat io or os modules as mandatory (redis compatibility)

### ISSUE THREAD

**Issue by drauschenbach** [Yonaba/Moses#66]
Amalgamated Lua scripts that inline Moses are unable to be loaded by Redis, due to its lack of support for the optional `io` and `os` modules, combined with its [strict](http://download.redis.io/redis-stable/deps/lua/etc/strict.lua) validator which ensures no Lua code is referencing a global that was not implicitly assigned.

Here's an example of a typical error message:

```sh
$ redis-cli --eval SparkPi-with-dependencies.lua 
(error) ERR Error running script (call to f_9ee542b8c203fc67d9dd0f620ee442e5ea6ecd9e): @user_script:36: user_script:36: attempt to index upvalue 'os' (a nil value)
``` 

Lines in Moses like this:

```lua
local clock = os.clock
```

Might need to change to something like this:

```lua
local clock = os and os.clock or nil
```

**Comment by drauschenbach** [comment]
Work-around in related work: https://github.com/BixData/lua-amalg-redis/commit/b0ce0adc82f13caf83fe70dd51d4d65531baa608

**Comment by Yonaba** [comment]
@drauschenbach , please let me know how commit a7fe26b works for you.

Roland.

**Comment by drauschenbach** [comment]
Verified. Nice!!

**Comment by drauschenbach** [comment]
FYI @Yonaba, [I demoed Moses running within Redis](https://www.slideshare.net/DavidRauschenbach/developing-and-deploying-edge-analytics-with-redis) at RedisConf19!
