### ISSUE TITLE
Feature request: mapi()

### ISSUE THREAD

**Issue by edubart** [Yonaba/Moses#68]
I do miss a `mapi()` function, it would work like `map()` but use `ipairs()` instead of `pairs()`.
Motivation: That are some tables that we are sure that they are just an array and `ipairs` is much faster on LuaJIT.

**Comment by edubart** [comment]
Never mind, I ended up needing many additional functions, it's straightforward to extended the library.

**Comment by Yonaba** [comment]
I found the idea interesting. It is now part of the API.

Thanks!
